name: 'cfn-nag-action'
description: 'CloudFormation Static Code Analysis Tool Suite with cfn-nag'
author: rsahu@sierrawireless.com
inputs:
  cloudformation_directory:
    description: 'directory within git repo to scan cloudformation templates'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setting python venv and cfn-naf
      continue-on-error: true
      shell: bash
      run: |
          sudo apt-get upgrade
          sudo apt-get update && 
          sudo apt-get install ruby -y
          gem install cfn-nag

    - name: Run CFN nag
      continue-on-error: true
      shell: bash
      run: |
          cfn_nag_scan --input-path ${{ inputs.cloudformation_directory }}

    # - name: setup & Run
    #   uses: stelligent/cfn_nag@master
    #   with:
    #     input_path: ${{ inputs.cloudformation_directory }}
    #     extra_args: --fail-on-warnings
        
    - name: Archive output
      uses: actions/upload-artifact@v3
      with:
        name: cnf-nag-artifact
        path: ${{ github.workspace }}/cfn_nag.out

